server:
  port: 8010
spring:
  application:
    name: standardarticleservice
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: standardarticledb
      username: admin
      password: password
  jpa:
    hibernate:
      ddl-auto: update